---
Description: "Create Drupal Stack Resources"

Parameters:
  KeyName:
    Type: String
  EC2InstanceTag:
    Type: String
  EC2InstanceType:
    Type: String
    Default: t2.micro
  SecurityGroupId:
    Type: String
    Default: sg-f42f0390
  EC2ImageId:
    Type: String
    Default: ami-374db956
  AvailabilityZone:
    Type: String
  SubnetId:
    Type: String
  EC2MinCount:
    Type: String
    Default: 1
  EC2MaxCount:
    Type: String
    Default: 1
  RDSPort:
    Type: String
    Default: 3306
  RDSEngine:
    Type: String
    Default: MySQL
  RDSInstanceClass:
    Type: String
    Default: db.t2.micro
  RDSSnapshotIdentifier:
    Type: String

#  EC2ProvisionScriptUrl:
#    Type: String
#    Default: https://raw.githubusercontent.com/tanyixiu/automation_deployment/master/ansible/roles/create_stack/files/drupal_server_provision.sh



Resources:
  MyElasticLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      CrossZone: true
      AvailabilityZones:
        - !Ref AvailabilityZone
      SecurityGroups:
        - !Ref SecurityGroupId
      Listeners:
        - LoadBalancerPort: 80
          InstancePort: 80
          Protocol: HTTP

  MyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: !Ref EC2MinCount
      MaxSize: !Ref EC2MaxCount
      LaunchConfigurationName: !Ref MyLaunchConfig
      AvailabilityZones:
        - !Ref AvailabilityZone
      VPCZoneIdentifier:
        - !Ref SubnetId
      LoadBalancerNames:
        - !Ref MyElasticLoadBalancer

  MyLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      KeyName: !Ref KeyName
      ImageId: !Ref EC2ImageId
      InstanceType: !Ref EC2InstanceType
      AssociatePublicIpAddress: true
      SecurityGroups:
        - !Ref SecurityGroupId
#      UserData:
#        Fn::Base64: !Join ["\n",["#include",!Ref EC2ProvisionScriptUrl ]]

  MyRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSnapshotIdentifier: !Ref RDSSnapshotIdentifier
      DBInstanceClass: !Ref RDSInstanceClass
      Engine: !Ref RDSEngine
      Port: !Ref RDSPort
      AvailabilityZone: !Ref AvailabilityZone
      PubliclyAccessible: true
      BackupRetentionPeriod: "0"


Outputs:
  ElbDNS:
    Description: "The ELB DNS Name"
    Value: !GetAtt [MyElasticLoadBalancer, DNSName]

  AutoScalingGroup:
    Description: "MyAutoScalingGroup"
    Value: !Ref MyAutoScalingGroup

  RDSHost:
    Description: "The host of RDS"
    Value: !GetAtt ["MyRDSInstance", "Endpoint.Address"]