---
- name: create drupal stack
  hosts: localhost
  gather_facts: false
  vars_files:
  - 'vars/{{ env }}/aws.yml'
  - 'vars/{{ env }}/artefact.yml'
  - 'vars/{{ env }}/common.yml'

  roles:
  - resources/create_resources
