- name: Create Drupal stack
  hosts: localhost
  gather_facts: false
  vars_files:
  - 'vars/{{ env }}/aws.yml'
  - 'vars/{{ env }}/drupal.yml'
  - 'vars/{{ env }}/common.yml'

  roles:
  - resources/resources
