---
- name: get drupal resources
  hosts: localhost
  gather_facts: false
  vars_files:
  - 'vars/{{ env }}/aws.yml'
  roles:
  - resources/get_resources


- name: deploy drupal application
  hosts: webserver
  become: true
  gather_facts: true
  roles:
  - deploy/config_application
  - deploy/download_artefacts