---
- name: get drupal resources
  hosts: localhost
  gather_facts: false
  vars_files:
    - 'vars/{{ env }}.yml'
  roles:
    - resources/get_resources/get_rds_host


- name: generate artefacts
  hosts: localhost
  gather_facts: false
  vars_files:
    - 'vars/{{ env }}.yml'
  vars:
    rds_host: "{{ hostvars['localhost'].rds_host }}"
  roles:
    - artefacts/generate_artefacts