---
- name: get drupal resources
  hosts: localhost
  gather_facts: false
  vars_files:
    - 'vars/{{ env }}.yml'
  roles:
    - resources/get_resources/get_ec2_host


- name: provision drupal resources
  hosts: webserver
  become: true
  gather_facts: true
  roles:
    - provision/install_tools
    - provision/config_access